apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-options: PruneLast=true
  name: argocd-test-app-simple
spec:
  destination:
    name: in-cluster
    namespace: argocd-test-app-simple
  project: argocd-test-app-simple
  source:
    repoURL: https://github.com/david-martin/argocd-test-app.git
    targetRevision: main
    path: argocd-test-app-simple
  syncPolicy:
    automated:
      selfHeal: true # Required to reset Observability CR changes that OLM sets to defaults 
    syncOptions:
    - ApplyOutOfSyncOnly=true