apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd-test-app
spec:
  destinations:
  - namespace: argocd-test-app,argocd-test-ingress-managedfields
    name: in-cluster
  clusterResourceWhitelist:
    - group: 'rbac.authorization.k8s.io'
      kind: 'ClusterRole'
    - group: 'rbac.authorization.k8s.io'
      kind: 'ClusterRoleBinding'
    - group: ''
      kind: 'Namespace'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'

