kind: Secret
apiVersion: v1
metadata:
  name: secret-with-vault-placeholder
  annotations:
    # vault kv get hybrid-cloud-gateway/testsecret
    avp.kubernetes.io/path: "hybrid-cloud-gateway/testsecret"
    avp.kubernetes.io/kv-version: 2
    avp.kubernetes.io/secret-version: 1
type: Opaque
data:
  password: <testkey>