kind: Secret
apiVersion: v1
metadata:
  name: secret-with-vault-placeholder
  annotations:
    avp.kubernetes.io/kv-version: "2"
    avp.kubernetes.io/path: hybrid-cloud-gateway/data/testsecret
    avp.kubernetes.io/secret-version: "1"
type: Opaque
data:
  testkey1: <testkey>
  testkey2: <path:hybrid-cloud-gateway/data/testsecret#testkey>
  testkey3: <path:hybrid-cloud-gateway/data/testsecret#testkey#1>